1. 데이터 벡터 다루기

    [예제] A 회사의 2010년 월별매출액 데이터가 다음과 같이 주어졌다고 하자.
    
    100, 120, 130, 124, 150, 167, 170, 163, 160, 155, 145, 157
    
    지수(index)를 이용하여 데이터벡터를 다루어 보기로 한다.

In [1]:
import numpy as np
x=np.array([100, 120, 130, 124, 150, 167, 170, 163, 160, 155, 145, 157])
x

array([100, 120, 130, 124, 150, 167, 170, 163, 160, 155, 145, 157])

In [2]:
x[1]

120

In [3]:
x[1:3]

array([120, 130])

In [4]:
x[1:4]

array([120, 130, 124])

In [5]:
x[-1]

157

In [6]:
x[-3]

155

In [7]:
x[1:-3]

array([120, 130, 124, 150, 167, 170, 163, 160])

In [8]:
x[7:]

array([163, 160, 155, 145, 157])

In [9]:
x[:3]

array([100, 120, 130])

In [10]:
x[::2]

array([100, 130, 150, 170, 160, 145])

In [11]:
x[1:4:2]

array([120, 124])

In [12]:
x>2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [17]:
x2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
x2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
x2[0]

array([1, 2, 3, 4])

In [20]:
x2[0,]

array([1, 2, 3, 4])

In [21]:
x2[0,:]

array([1, 2, 3, 4])

In [22]:
x2[0,1]

2

In [23]:
x2[:2,1]

array([2, 6])

In [24]:
x2[:2,]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
x2>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
x2[x2>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
#데이터 프레임 생성
import pandas as pd
df=pd.DataFrame({
    'name':['Kim','Lee','Park','Bae','Kang'],
    'age': [24,32,43,24,30],
    'height':[160,170,165,173,158]
})
df

name  age  height
0   Kim   24     160
1   Lee   32     170
2  Park   43     165
3   Bae   24     173
4  Kang   30     158

In [30]:
#나이를 기준으로 순위를 주어. rank_average 변수 생성 -> rank() 사용

df['rank_average']=df['age'].rank(method='min', ascending=False) #method='min': 동점일 경우 최솟값을 줌
df                                                               #ascending=False: 내림차순으로 순위를 줌 (값이 클수록 높은 순위)

name  age  height  rank_average
0   Kim   24     160           4.0
1   Lee   32     170           2.0
2  Park   43     165           1.0
3   Bae   24     173           4.0
4  Kang   30     158           3.0

In [31]:
df['age'].rank(method='max',ascending=False) #method='max' 동점일 경우 최댓값을 줌

0    5.0
1    2.0
2    1.0
3    5.0
4    3.0
Name: age, dtype: float64

In [32]:
df['age'].rank(method='average',ascending=False) #method='average' 동점일 경우 평균을 줌 default

0    4.5
1    2.0
2    1.0
3    4.5
4    3.0
Name: age, dtype: float64

In [34]:
df['age'].rank(ascending=False)

0    4.5
1    2.0
2    1.0
3    4.5
4    3.0
Name: age, dtype: float64

In [35]:
#결측값 포함한 데이터 프레임인 경우

df2=pd.DataFrame({
    'name':['Kim','Lee','Park','Bae','Kang'],
    'age':[24,32,43,24,np.nan],
    'height':[160,170,165,173,158]
})
df2

name   age  height
0   Kim  24.0     160
1   Lee  32.0     170
2  Park  43.0     165
3   Bae  24.0     173
4  Kang   NaN     158

In [36]:
#결측값 처리 위한 옵션 na_option 추가

df2['rank_average']=df2['age'].rank(method='min', ascending=False, na_option='bottom')
#na_option='bottom': 결측값에 후순위를 주고자 할 경우
#na_option='top': 결측값에 선순위를 주고자 할 경우
#na_option='keep': 결측값을 NaN으로 두고자 할 경우 default
df2

name   age  height  rank_average
0   Kim  24.0     160           3.0
1   Lee  32.0     170           2.0
2  Park  43.0     165           1.0
3   Bae  24.0     173           3.0
4  Kang   NaN     158           5.0

In [37]:
#데이터 프레임 df에서 name변수 기준으로 오름차순 정렬하기

df_sort=df.sort_values(by='name')
df_sort

name  age  height  rank_average
3   Bae   24     173           4.0
4  Kang   30     158           3.0
0   Kim   24     160           4.0
1   Lee   32     170           2.0
2  Park   43     165           1.0

In [40]:
#데이터 프레임 df에서 age 변수 기준으로 오름차순 정렬하기
df_sort=df.sort_values(by='age')
df_sort

name  age  height  rank_average
0   Kim   24     160           4.0
3   Bae   24     173           4.0
4  Kang   30     158           3.0
1   Lee   32     170           2.0
2  Park   43     165           1.0

In [42]:
#데이터 프레임 df에서 height 변수 기준으로 내림차순으로 정렬하기

df_sort=df.sort_values(by='height', ascending=False)
df_sort

name  age  height  rank_average
3   Bae   24     173           4.0
1   Lee   32     170           2.0
2  Park   43     165           1.0
0   Kim   24     160           4.0
4  Kang   30     158           3.0

In [43]:
#데이터 프레임 df에서 두 변수 age, height 변수 기준으로 오름차순으로 정렬하기
df_sort=df.sort_values(by=['age','height'])
df_sort

name  age  height  rank_average
0   Kim   24     160           4.0
3   Bae   24     173           4.0
4  Kang   30     158           3.0
1   Lee   32     170           2.0
2  Park   43     165           1.0

In [46]:
#데이터 프레임 df2에 결측값 포함 여부 확인하기

df2.isnull().values.any() #True:결측값 포함

True

In [47]:
#데이터 프레임 df2 결측값에 0으로 대체하기

df2_0=df2.fillna(0)
df2_0

name   age  height  rank_average
0   Kim  24.0     160           3.0
1   Lee  32.0     170           2.0
2  Park  43.0     165           1.0
3   Bae  24.0     173           3.0
4  Kang   0.0     158           5.0

In [49]:
#결측값을 변수별 평균으로 대체
df_mean=df2.fillna(df2.mean(numeric_only=True))
df_mean

name    age  height  rank_average
0   Kim  24.00     160           3.0
1   Lee  32.00     170           2.0
2  Park  43.00     165           1.0
3   Bae  24.00     173           3.0
4  Kang  30.75     158           5.0

In [50]:
#순서상 결측값의 바로 앞의 값으로 대체하기

df2_f=df2.fillna(method='ffill')
df2_f

name   age  height  rank_average
0   Kim  24.0     160           3.0
1   Lee  32.0     170           2.0
2  Park  43.0     165           1.0
3   Bae  24.0     173           3.0
4  Kang  24.0     158           5.0

In [51]:
#순서상 결측값의 바로 뒤의 값으로 대체하기

df2_f=df2.fillna(method='backfill')
df2_f

name   age  height  rank_average
0   Kim  24.0     160           3.0
1   Lee  32.0     170           2.0
2  Park  43.0     165           1.0
3   Bae  24.0     173           3.0
4  Kang   NaN     158           5.0

In [53]:
df3=df2.sort_values(by='height')
df3

name   age  height  rank_average
4  Kang   NaN     158           5.0
0   Kim  24.0     160           3.0
2  Park  43.0     165           1.0
1   Lee  32.0     170           2.0
3   Bae  24.0     173           3.0

In [54]:
df3_f=df3.fillna(method='backfill')
df3_f

name   age  height  rank_average
4  Kang  24.0     158           5.0
0   Kim  24.0     160           3.0
2  Park  43.0     165           1.0
1   Lee  32.0     170           2.0
3   Bae  24.0     173           3.0

In [55]:
df3_f2=df2.sort_values(by='height').fillna(method='backfill')
df3_f2

name   age  height  rank_average
4  Kang  24.0     158           5.0
0   Kim  24.0     160           3.0
2  Park  43.0     165           1.0
1   Lee  32.0     170           2.0
3   Bae  24.0     173           3.0

In [60]:
df2.sort_values(by='height').fillna(method='backfill')[['name','age']]

name   age
4  Kang  24.0
0   Kim  24.0
2  Park  43.0
1   Lee  32.0
3   Bae  24.0